config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#home_page" 
  get "apps/app_add_ids"
  get "apps/app_frames"
  get "home/api_help"
  resources :app_devices
  resources :devices
  resources :app_frames
  resources :app_adds
  resources :apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_frame.rb
class AppFrame < ApplicationRecord
  belongs_to :app
	mount_uploader :frame, AppLogoUploader
end

app/controllers/app_frames_controller.rb
class AppFramesController < ApplicationController
  before_action :set_app_frame, only: [:show, :edit, :update, :destroy]

  # GET /app_frames
  # GET /app_frames.json
  def index
    @app_frames = AppFrame.all
  end

  # GET /app_frames/1
  # GET /app_frames/1.json
  def show
  end

  # GET /app_frames/new
  def new
    @app_frame = AppFrame.new
  end

  # GET /app_frames/1/edit
  def edit
  end

  # POST /app_frames
  # POST /app_frames.json
  def create
    @app_frame = AppFrame.new(app_frame_params)

    respond_to do |format|
      if @app_frame.save
        format.html { redirect_to @app_frame, notice: 'App frame was successfully created.' }
        format.json { render :show, status: :created, location: @app_frame }
      else
        format.html { render :new }
        format.json { render json: @app_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_frames/1
  # PATCH/PUT /app_frames/1.json
  def update
    respond_to do |format|
      if @app_frame.update(app_frame_params)
        format.html { redirect_to @app_frame, notice: 'App frame was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_frame }
      else
        format.html { render :edit }
        format.json { render json: @app_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_frames/1
  # DELETE /app_frames/1.json
  def destroy
    @app_frame.destroy
    respond_to do |format|
      format.html { redirect_to app_frames_url, notice: 'App frame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_frame
      @app_frame = AppFrame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_frame_params
      params.require(:app_frame).permit(:app_id, :frame, :is_visible)
    end
end

app/helpers/app_frames_helper.rb
module AppFramesHelper
end

app/views/app_frames/_form.html.erb
<%= form_with(model: app_frame, local: true) do |form| %>
  <% if app_frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_frame.errors.count, "error") %> prohibited this app_frame from being saved:</h2>

      <ul>
      <% app_frame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :app_id %>
    <%= form.select :app_id, App.all.collect {|a| [ a.name, a.id ] } %>
  </div>

  <div class="field">
    <%= form.label :frame %>
    <%= form.hidden_field(:frame_cache) %>

    <%= form.file_field :frame, id: :app_frame_frame %>
  </div>

  <div class="field">
    <%= form.label :is_visible %>
    <%= form.check_box :is_visible, id: :app_frame_is_visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/app_frames/edit.html.erb
<h1>Editing App Frame</h1>

<%= render 'form', app_frame: @app_frame %>

<%= link_to 'Show', @app_frame %> |
<%= link_to 'Back', app_frames_path %>

app/views/app_frames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Frames</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Frame</th>
      <th>Is visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_frames.each do |app_frame| %>
      <tr>
        <td><%= app_frame.app.try(:name) %></td>
        <td><%= image_tag(app_frame.frame.url,class: "img_thumb") %></td>
        <td><%= app_frame.is_visible %></td>
        <td><%= link_to 'Show', app_frame %></td>
        <td><%= link_to 'Edit', edit_app_frame_path(app_frame) %></td>
        <td><%= link_to 'Destroy', app_frame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Frame', new_app_frame_path %>

app/views/app_frames/new.html.erb
<h1>New App Frame</h1>

<%= render 'form', app_frame: @app_frame %>

<%= link_to 'Back', app_frames_path %>

app/views/app_frames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @app_frame.app %>
</p>

<p>
  <strong>Frame:</strong>
  <%= @app_frame.frame %>
</p>

<p>
  <strong>Is visible:</strong>
  <%= @app_frame.is_visible %>
</p>

<%= link_to 'Edit', edit_app_frame_path(@app_frame) %> |
<%= link_to 'Back', app_frames_path %>