config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#home_page" 
  get "apps/app_add_ids"
  get "apps/app_frames"
  get "home/api_help"
  resources :app_devices
  resources :devices
  resources :app_frames
  resources :app_adds
  resources :apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_add.rb
class AppAdd < ApplicationRecord
  belongs_to :app
  belongs_to :ad_type
end

app/controllers/app_adds_controller.rb
class AppAddsController < ApplicationController
  before_action :set_app_add, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /app_adds
  # GET /app_adds.json
  def index
    @app_adds = AppAdd.all
  end

  # GET /app_adds/1
  # GET /app_adds/1.json
  def show
  end

  # GET /app_adds/new
  def new
    @app_add = AppAdd.new
  end

  # GET /app_adds/1/edit
  def edit
  end

  # POST /app_adds
  # POST /app_adds.json
  def create
    exit
    @app_add = AppAdd.new(app_add_params)

    respond_to do |format|
      if @app_add.save
        format.html { redirect_to @app_add, notice: 'App add was successfully created.' }
        format.json { render :show, status: :created, location: @app_add }
      else
        format.html { render :new }
        format.json { render json: @app_add.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_adds/1
  # PATCH/PUT /app_adds/1.json
  def update
    respond_to do |format|
      if @app_add.update(app_add_params)
        format.html { redirect_to @app_add, notice: 'App add was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_add }
      else
        format.html { render :edit }
        format.json { render json: @app_add.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_adds/1
  # DELETE /app_adds/1.json
  def destroy
    @app_add.destroy
    respond_to do |format|
      format.html { redirect_to app_adds_url, notice: 'App add was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_add
      @app_add = AppAdd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_add_params
      params.require(:app_add).permit(:app_id, :name, :ad_mob_id, :fb_id, :is_shown, :is_fb, :is_ad_mob)
    end
end

app/helpers/app_adds_helper.rb
module AppAddsHelper
end

app/views/app_adds/_form.html.erb
<%= form_with(model: app_add, local: true) do |form| %>
  <% if app_add.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_add.errors.count, "error") %> prohibited this app_add from being saved:</h2>

      <ul>
      <% app_add.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :app_id %>
    <%= form.select :app_id, App.all.collect {|a| [ a.name, a.id ] } %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Ad Name</th>
        <th>Ad Mob Id</th>
        <th>Fb Id</th>
        <th>Is Shown</th>
        <th>Is Ad Mob</th>
        <th>Is Fb</th>
      </tr>
    </thead>
    <tbody>
      <% AdType.all.each do |ad_type| %>
        <tr>
          <td><%= ad_type.name %><input id="app_add_ad_mob_id" value="<%= ad_type.id %>" type="hidden" name="app_adds[][ad_type_id]"></td>
          <td><input id="app_add_ad_mob_id" type="text" name="app_adds[][ad_mob_id]"></td>
          <td><input id="app_add_fb_id" type="text" name="app_adds[][fb_id]"></td>
          <td><input id="app_add_is_shown" type="checkbox" value="1" checked="checked" name="app_adds[][is_shown]"></td>
          <td><input id="app_add_is_ad_mob" type="checkbox" value="1" name="app_adds[][is_ad_mob]"></td>
          <td><input id="app_add_is_fb" type="checkbox" value="1" name="app_adds[][is_fb]"></td>
        </tr>
      <% end %>

    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/app_adds/edit.html.erb
<h1>Editing App Add</h1>

<%= render 'form', app_add: @app_add %>

<%= link_to 'Show', @app_add %> |
<%= link_to 'Back', app_adds_path %>

app/views/app_adds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>App Adds</h1>

<table>
  <thead>
    <tr>
      <th>App</th>
      <th>Name</th>
      <th>Ad mob</th>
      <th>Fb</th>
      <th>Is shown</th>
      <th>Is fb</th>
      <th>Is ad mob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_adds.each do |app_add| %>
      <tr>
        <td><%= app_add.app.try(:name) %></td>
        <td><%= app_add.name %></td>
        <td><%= app_add.ad_mob_id %></td>
        <td><%= app_add.fb_id %></td>
        <td><%= app_add.is_shown %></td>
        <td><%= app_add.is_fb %></td>
        <td><%= app_add.is_ad_mob %></td>
        <td><%= link_to 'Show', app_add %></td>
        <td><%= link_to 'Edit', edit_app_add_path(app_add) %></td>
        <td><%= link_to 'Destroy', app_add, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App Add', new_app_add_path %>

app/views/app_adds/new.html.erb
<h1>New App Add</h1>

<%= render 'form', app_add: @app_add %>

<%= link_to 'Back', app_adds_path %>

app/views/app_adds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @app_add.app.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @app_add.name %>
</p>

<p>
  <strong>Ad mob:</strong>
  <%= @app_add.ad_mob_id %>
</p>

<p>
  <strong>Fb:</strong>
  <%= @app_add.fb_id %>
</p>

<p>
  <strong>Is shown:</strong>
  <%= @app_add.is_shown %>
</p>

<p>
  <strong>Is fb:</strong>
  <%= @app_add.is_fb %>
</p>

<p>
  <strong>Is ad mob:</strong>
  <%= @app_add.is_ad_mob %>
</p>

<%= link_to 'Edit', edit_app_add_path(@app_add) %> |
<%= link_to 'Back', app_adds_path %>